const userController = require("../controller/user.controller")
const router = require("express").Router()
const auth = require("../middleware/auth")
router.post("/add", userController.add)
router.post("/login", userController.login)
router.post("/logout",auth, userController.logOut)
router.post("/logoutAll",auth, userController.logOutAll)
router.post("/changePass",auth, userController.changePass)
router.get('/all', auth, userController.all)
router.get('/all/:id', auth, userController.single)
router.delete('/all/:id', auth, userController.del)
router.patch('/all/:id', auth, userController.edit)
router.patch('/all', auth, userController.editWithToken)
module.exports = router